
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef CLIPPER_H
#define CLIPPER_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "Clipper.tables.h"

static_inline fix16_t Clipper_cubic_clipper(fix16_t x){
   if(x <= -0xaaaa /* -0.666667 */){
      return -0xaaaa /* -0.666667 */;
   }
   else
   {
      if(x >= 0xaaaa /* 0.666667 */){
         return 0xaaaa /* 0.666667 */;
      }
      else
      {
         return (x + fix_mul(fix_mul(fix_mul(-0x5555 /* -0.333333 */,x),x),x));
      }
   }
};

static_inline fix16_t Clipper_process(fix16_t x){
   return Clipper_cubic_clipper(x);
};



#endif // CLIPPER_H
