
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Saw.h"

void Saw__ctx_type_10_init(Saw__ctx_type_10 &_output_){
   Saw__ctx_type_10 _ctx;
   _ctx.rate = 0x0 /* 0.000000 */;
   _ctx.phase = 0x0 /* 0.000000 */;
   Saw__ctx_type_0_init(_ctx._inst1ac);
   _output_ = _ctx;
   return ;
}

fix16_t Saw_process(Saw__ctx_type_10 &_ctx, fix16_t cv){
   fix16_t y;
   y = 0x0 /* 0.000000 */;
   if(Saw_change(_ctx._inst1ac,cv)){
      _ctx.rate = Saw_cvToRate(cv);
   }
   _ctx.phase = (_ctx.phase + (_ctx.rate << 1));
   if(_ctx.phase > (0x10000 /* 1.000000 */ + (- _ctx.rate))){
      y = (-0x10000 /* -1.000000 */ + _ctx.phase + (- fix_div(_ctx.phase,_ctx.rate)) + fix_div(0x10000 /* 1.000000 */,_ctx.rate));
      _ctx.phase = (-0x20000 /* -2.000000 */ + _ctx.phase);
   }
   else
   {
      y = _ctx.phase;
   }
   return y;
}


