
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Ahr.h"

void Ahr__ctx_type_1_init(Ahr__ctx_type_1 &_output_){
   Ahr__ctx_type_1 _ctx;
   _ctx.target = 0x0 /* 0.000000 */;
   _ctx.state = 0;
   _ctx.rate = 0x0 /* 0.000000 */;
   _ctx.out = 0x0 /* 0.000000 */;
   _ctx.hold_phase = 0x0 /* 0.000000 */;
   Ahr__ctx_type_0_init(_ctx._inst3cd);
   Ahr__ctx_type_0_init(_ctx._inst1cd);
   _output_ = _ctx;
   return ;
}

fix16_t Ahr_process(Ahr__ctx_type_1 &_ctx, fix16_t gate, fix16_t a, fix16_t h, fix16_t r){
   int release;
   release = 0;
   int attack;
   attack = 1;
   int hold;
   hold = 2;
   int reset;
   reset = 3;
   uint8_t bgate;
   bgate = (gate > 0x0 /* 0.000000 */);
   if(Ahr_edge(_ctx._inst1cd,bgate)){
      _ctx.state = reset;
   }
   if(Ahr_edge(_ctx._inst3cd,(_ctx.out > 0x4000000 /* 1024.000000 */))){
      _ctx.hold_phase = 0x0 /* 0.000000 */;
      _ctx.state = hold;
   }
   if((_ctx.out < 0xa0000 /* 10.000000 */) && (_ctx.state == reset)){
      _ctx.state = attack;
   }
   if((_ctx.hold_phase > 0x640000 /* 100.000000 */) && (_ctx.state == hold)){
      _ctx.state = release;
   }
   if(_ctx.state == reset){
      _ctx.rate = 0xfd77 /* 0.990099 */;
      _ctx.target = 0x0 /* 0.000000 */;
   }
   if(_ctx.state == attack){
      _ctx.rate = fix_div(0x10000 /* 1.000000 */,(0x28f /* 0.010000 */ + fix_mul(0x640000 /* 100.000000 */,a)));
      _ctx.target = 0x4cccccc /* 1228.800000 */;
   }
   if(_ctx.state == hold){
      fix16_t hrate;
      hrate = fix_div(0x10000 /* 1.000000 */,(0x28f /* 0.010000 */ + fix_mul(0x640000 /* 100.000000 */,h)));
      _ctx.hold_phase = (_ctx.hold_phase + hrate);
   }
   if(_ctx.state == release){
      _ctx.rate = fix_div(0x10000 /* 1.000000 */,(0x28f /* 0.010000 */ + fix_mul(0x640000 /* 100.000000 */,r)));
      _ctx.target = 0x0 /* 0.000000 */;
   }
   _ctx.out = (_ctx.out + fix_mul(fix_mul(0x147 /* 0.005000 */,_ctx.rate),(_ctx.target + (- _ctx.out))));
   return fix_clip((_ctx.out >> 10),0x0 /* 0.000000 */,0x10000 /* 1.000000 */);
}


