
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef FOLD_H
#define FOLD_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"

fix16_t Fold_do(fix16_t signal, fix16_t level);

static_inline fix16_t Fold_process(fix16_t signal, fix16_t level){
   return Fold_do(signal,level);
};



#endif // FOLD_H
