
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef DLINE_H
#define DLINE_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "Dline.tables.h"

static_inline fix16_t Dline_tanh_table_raw_c0(int index){
   return Dline_tanh_table_c0[index];
};

static_inline fix16_t Dline_tanh_table_raw_c1(int index){
   return Dline_tanh_table_c1[index];
};

static_inline fix16_t Dline_tanh_table_raw_c2(int index){
   return Dline_tanh_table_c2[index];
};

static_inline fix16_t Dline_tanh_table(fix16_t x){
   int index;
   index = int_clip(fix_to_int(fix_mul(0x50000 /* 5.000000 */,(0x180000 /* 24.000000 */ + x))),0,240);
   return (fix_wrap_array(Dline_tanh_table_c0)[index] + fix_mul(x,(fix_wrap_array(Dline_tanh_table_c1)[index] + fix_mul(x,fix_wrap_array(Dline_tanh_table_c2)[index]))));
}

static_inline fix16_t Dline_saturate(fix16_t x){
   return Dline_tanh_table(x);
};

typedef struct Dline__ctx_type_5 {
   fix16_t x4;
   fix16_t x3;
   fix16_t x2;
} Dline__ctx_type_5;

typedef Dline__ctx_type_5 Dline_soft_type;

void Dline__ctx_type_5_init(Dline__ctx_type_5 &_output_);

static_inline void Dline_soft_init(Dline__ctx_type_5 &_output_){
   Dline__ctx_type_5_init(_output_);
   return ;
}

fix16_t Dline_soft(Dline__ctx_type_5 &_ctx, fix16_t x1);

typedef struct Dline__ctx_type_6 {
   int write_pos;
   fix16_t buffer[1000];
} Dline__ctx_type_6;

typedef Dline__ctx_type_6 Dline_do_type;

void Dline__ctx_type_6_init(Dline__ctx_type_6 &_output_);

static_inline void Dline_do_init(Dline__ctx_type_6 &_output_){
   Dline__ctx_type_6_init(_output_);
   return ;
}

fix16_t Dline_do(Dline__ctx_type_6 &_ctx, fix16_t x, fix16_t time, fix16_t feedback);

typedef struct Dline__ctx_type_7 {
   Dline__ctx_type_6 _inst2d6;
   Dline__ctx_type_5 _inst139;
} Dline__ctx_type_7;

typedef Dline__ctx_type_7 Dline_process_type;

void Dline__ctx_type_7_init(Dline__ctx_type_7 &_output_);

static_inline void Dline_process_init(Dline__ctx_type_7 &_output_){
   Dline__ctx_type_7_init(_output_);
   return ;
}

static_inline fix16_t Dline_process(Dline__ctx_type_7 &_ctx, fix16_t x, fix16_t time, fix16_t feedback){
   return Dline_do(_ctx._inst2d6,x,Dline_soft(_ctx._inst139,time),feedback);
};



#endif // DLINE_H
