
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#ifndef SAW_H
#define SAW_H
#include <stdint.h>
#include <math.h>
#include "vultin.h"
#include "Saw.tables.h"

typedef struct Saw__ctx_type_0 {
   fix16_t pre_x;
} Saw__ctx_type_0;

typedef Saw__ctx_type_0 Saw_change_type;

static_inline void Saw__ctx_type_0_init(Saw__ctx_type_0 &_output_){
   Saw__ctx_type_0 _ctx;
   _ctx.pre_x = 0x0 /* 0.000000 */;
   _output_ = _ctx;
   return ;
}

static_inline void Saw_change_init(Saw__ctx_type_0 &_output_){
   Saw__ctx_type_0_init(_output_);
   return ;
}

static_inline uint8_t Saw_change(Saw__ctx_type_0 &_ctx, fix16_t x){
   uint8_t v;
   v = (_ctx.pre_x != x);
   _ctx.pre_x = x;
   return v;
}

static_inline fix16_t Saw_pitchToRate_raw_c0(int index){
   return Saw_pitchToRate_c0[index];
};

static_inline fix16_t Saw_pitchToRate_raw_c1(int index){
   return Saw_pitchToRate_c1[index];
};

static_inline fix16_t Saw_pitchToRate_raw_c2(int index){
   return Saw_pitchToRate_c2[index];
};

static_inline fix16_t Saw_pitchToRate(fix16_t pitch){
   int index;
   index = int_clip(fix_to_int(fix_mul(0x3e7c /* 0.244094 */,pitch)),0,31);
   return (fix_wrap_array(Saw_pitchToRate_c0)[index] + fix_mul(pitch,(fix_wrap_array(Saw_pitchToRate_c1)[index] + fix_mul(pitch,fix_wrap_array(Saw_pitchToRate_c2)[index]))));
}

static_inline fix16_t Saw_cvToPitch(fix16_t cv){
   return (0x180000 /* 24.000000 */ + fix_mul(0x780000 /* 120.000000 */,cv));
};

static_inline fix16_t Saw_cvToRate_raw_c0(int index){
   return Saw_cvToRate_c0[index];
};

static_inline fix16_t Saw_cvToRate_raw_c1(int index){
   return Saw_cvToRate_c1[index];
};

static_inline fix16_t Saw_cvToRate_raw_c2(int index){
   return Saw_cvToRate_c2[index];
};

static_inline fix16_t Saw_cvToRate(fix16_t cv){
   int index;
   index = int_clip(fix_to_int(fix_mul(0x8d1c71 /* 141.111111 */,cv)),0,127);
   return (fix_wrap_array(Saw_cvToRate_c0)[index] + fix_mul(cv,(fix_wrap_array(Saw_cvToRate_c1)[index] + fix_mul(cv,fix_wrap_array(Saw_cvToRate_c2)[index]))));
}

typedef struct Saw__ctx_type_10 {
   fix16_t rate;
   fix16_t phase;
   Saw__ctx_type_0 _inst1ac;
} Saw__ctx_type_10;

typedef Saw__ctx_type_10 Saw_process_type;

void Saw__ctx_type_10_init(Saw__ctx_type_10 &_output_);

static_inline void Saw_process_init(Saw__ctx_type_10 &_output_){
   Saw__ctx_type_10_init(_output_);
   return ;
}

fix16_t Saw_process(Saw__ctx_type_10 &_ctx, fix16_t cv);



#endif // SAW_H
