
/* Code automatically generated by Vult https://github.com/modlfo/vult */
#include "Saw.h"

void Saw__ctx_type_11_init(Saw__ctx_type_11 &_output_){
   Saw__ctx_type_11 _ctx;
   _ctx.ptr_w2_ret_1 = 0x0 /* 0.000000 */;
   _ctx.ptr_w2_ret_0 = false;
   _output_ = _ctx;
   return ;
}

void Saw_ptr_w2(Saw__ctx_type_11 &_ctx, fix16_t phase, fix16_t rate){
   _tuple___bool_real__ out;
   fix16_t s1;
   s1 = rate;
   fix16_t s2;
   s2 = (rate + s1);
   if(phase < s1){
      fix16_t d;
      d = fix_div(phase,rate);
      fix16_t t2;
      t2 = (s2 >> 10);
      {
         out.field_0 = false;
         out.field_1 = (0x10000 /* 1.000000 */ + fix_mul(d,(t2 + (- d))));
      }
   }
   else
   {
      if(phase < s2){
         fix16_t d;
         d = fix_div(phase,rate);
         fix16_t t2;
         t2 = (s2 >> 10);
         {
            out.field_0 = false;
            out.field_1 = (0x30000 /* 3.000000 */ + fix_mul(d,(-0x40000 /* -4.000000 */ + d + t2)));
         }
      }
      else
      {
         out.field_0 = true;
         out.field_1 = 0x0 /* 0.000000 */;
      }
   }
   _ctx.ptr_w2_ret_0 = out.field_0;_ctx.ptr_w2_ret_1 = out.field_1;
   return ;
}

void Saw__ctx_type_12_init(Saw__ctx_type_12 &_output_){
   Saw__ctx_type_12 _ctx;
   _ctx.reset_state = false;
   _ctx.reset_phase = 0x0 /* 0.000000 */;
   _ctx.rate = 0x0 /* 0.000000 */;
   _ctx.phase = 0x0 /* 0.000000 */;
   Saw__ctx_type_11_init(_ctx._inst6d5);
   Saw__ctx_type_0_init(_ctx._inst35c);
   Saw__ctx_type_1_init(_ctx._inst1ac);
   _output_ = _ctx;
   return ;
}

fix16_t Saw_process(Saw__ctx_type_12 &_ctx, fix16_t cv, fix16_t reset){
   fix16_t transition;
   transition = 0x0 /* 0.000000 */;
   fix16_t out;
   out = 0x0 /* 0.000000 */;
   if(Saw_change(_ctx._inst1ac,cv)){
      _ctx.rate = Saw_cvToRate_1024(cv);
   }
   fix16_t new_phase;
   new_phase = (_ctx.phase + _ctx.rate);
   uint8_t do_reset;
   do_reset = Saw_edge(_ctx._inst35c,(reset > 0x0 /* 0.000000 */));
   uint8_t do_wrap;
   do_wrap = (new_phase > 0x4000000 /* 1024.000000 */);
   if(do_reset || do_wrap){
      _ctx.reset_phase = _ctx.phase;
      if(do_wrap){
         new_phase = (-0x4000000 /* -1024.000000 */ + new_phase);
      }
      else
      {
         new_phase = 0x0 /* 0.000000 */;
      }
      _ctx.reset_state = true;
   }
   _ctx.phase = new_phase;
   out = _ctx.phase;
   if(_ctx.reset_state){
      uint8_t done;
      fix16_t ptr;
      Saw_ptr_w2(_ctx._inst6d5,_ctx.phase,_ctx.rate);
      done = Saw_ptr_w2_ret_0(_ctx._inst6d5);
      ptr = Saw_ptr_w2_ret_1(_ctx._inst6d5);
      transition = (fix_mul(_ctx.reset_phase,(0x10000 /* 1.000000 */ + ptr)) >> 1);
      if(done){
         _ctx.reset_state = false;
      }
      else
      {
         out = transition;
      }
   }
   return (-0x10000 /* -1.000000 */ + (out >> 9));
}


